 
node_list:
  home: k8sworkersb-ubuntu-s-4vcpu-8gb-0-blr1
  node2: k8sworkersb-ubuntu-s-4vcpu-8gb-1-nyc1
  node3: k8sworkersb-ubuntu-s-4vcpu-8gb-2-fra1
  node4: k8sworkersb-ubuntu-s-4vcpu-8gb-3-fra1 
  node5: k8sworkersb-ubuntu-s-4vcpu-8gb-4-lon1
  node6: k8sworkersb-ubuntu-s-4vcpu-8gb-5-nyc3
  node7: k8sworkersb-ubuntu-s-4vcpu-8gb-6-tor1
  node8: k8sworkersb-ubuntu-s-4vcpu-8gb-7-tor1
  node9: k8sworkersb-ubuntu-s-4vcpu-8gb-8-tor1
  node10: k8sworkersb-ubuntu-s-4vcpu-8gb-9-ams3 
  #TODO: datasources will eventually be removed from here
  datasource1: k8sworkersb-ubuntu-s-4vcpu-8gb-13-ams3
  datasource2: k8sworkersb-ubuntu-s-4vcpu-8gb-14-nyc1
  datasource3: k8sworkersb-ubuntu-s-4vcpu-8gb-10-fra1
  datasource4: k8sworkersb-ubuntu-s-4vcpu-8gb-11-ams3
  datasource5: k8sworkersb-ubuntu-s-4vcpu-8gb-12-ams3
application:
  sources:
  - name: datasource1
    dataset: fireengine
    datapath: data/fireengine
    stream_image: docker.io/anrg/streams_home:fireengine
    #this should be a node that jupiter wont schedule nodes on   
    node_placement: k8sworkersb-ubuntu-s-4vcpu-8gb-13-ams3 
  - name: datasource2
    dataset: schoolbus
    datapath: data/schoolbus
    stream_image: docker.io/anrg/streams_home:schoolbus
    #this should be a node that jupiter wont schedule nodes on   
    node_placement: k8sworkersb-ubuntu-s-4vcpu-8gb-14-nyc1 
  - name: datasource3
    dataset: whitewolf
    datapath: data/whitewolf
    stream_image: docker.io/anrg/streams_home:whitewolf
    #this should be a node that jupiter wont schedule nodes on   
    node_placement: k8sworkersb-ubuntu-s-4vcpu-8gb-10-fra1 
  - name: datasource4
    dataset: hyena
    datapath: data/hyena
    stream_image: docker.io/anrg/streams_home:hyena
    #this should be a node that jupiter wont schedule nodes on   
    node_placement: k8sworkersb-ubuntu-s-4vcpu-8gb-11-ams3 
  - name: datasource5
    dataset: kitfox
    datapath: data/kitfox
    stream_image: docker.io/anrg/streams_home:kitfox
    #this should be a node that jupiter wont schedule nodes on   
    node_placement: k8sworkersb-ubuntu-s-4vcpu-8gb-12-ams3
  ports:
    # these ports are to be exposed by app docker containers and also exposed via k8s service
    # available range: 50000-60000
    - 57021
  num_tasks: 46 #base is 18, add 7 everytime adding a new set
  task_list:
    home: home  #TODO
    worker_tasks:
      - name: master
        # node_placement: n2
        inputs_to_wait_for: 9
        output_policy: BATCHED_CUSTOM_ORDER
        children:  # child order determines round robin sequence
          - resnet0
          - resnet1
          - resnet2
          - resnet3
          - resnet4
          - resnet5
          - resnet6
          - resnet7
          - resnet8
          - collage
        infile_prefix: n0
        outfile_prefix: master
        dag_task: True
      - name: resnet0
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
        infile_prefix: master
        outfile_prefix: resnet0
        dag_task: True
      - name: resnet1
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
        infile_prefix: master
        outfile_prefix: resnet1
        dag_task: True
      - name: resnet2
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
        infile_prefix: master
        outfile_prefix: resnet2
        dag_task: True
      - name: resnet3
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
        infile_prefix: master
        outfile_prefix: resnet3
        dag_task: True
      - name: resnet4
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
        infile_prefix: master
        outfile_prefix: resnet4
        dag_task: True
      - name: resnet5
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
        infile_prefix: master
        outfile_prefix: resnet5
        dag_task: True
      - name: resnet6
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
        infile_prefix: master
        outfile_prefix: resnet6
        dag_task: True
      - name: resnet7
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
        infile_prefix: master
        outfile_prefix: resnet7
        dag_task: True
      - name: resnet8
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
        infile_prefix: master
        outfile_prefix: resnet8
        dag_task: True
      - name: collage
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        infile_prefix: master
        outfile_prefix: collage
        dag_task: True
      - name: storeclass1
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children:
          - lccenc1
        infile_prefix: resnet
        outfile_prefix: storeclass1
        dag_task: True
      - name: storeclass2
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children:
          - lccenc2
        infile_prefix: resnet
        outfile_prefix: storeclass2
        dag_task: True
      - name: storeclass3
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children:
          - lccenc3
        infile_prefix: resnet
        outfile_prefix: storeclass3
        dag_task: True
      - name: storeclass4
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children:
          - lccenc4
        infile_prefix: resnet
        outfile_prefix: storeclass4
        dag_task: True
      - name: storeclass5
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children:
          - lccenc5
        infile_prefix: resnet
        outfile_prefix: storeclass5
        dag_task: True
      - name: lccenc1
        inputs_to_wait_for: 4
        output_policy: BATCHED_CUSTOM_ORDER
        children:
          - score1a
          - score1b
          - score1c
        infile_prefix: storeclass1
        outfile_prefix: lccenc1
        dag_task: True
      - name: lccenc2
        inputs_to_wait_for: 4
        output_policy: BATCHED_CUSTOM_ORDER
        children:
          - score2a
          - score2b
          - score2c
        infile_prefix: storeclass2
        outfile_prefix: lccenc2
        dag_task: True
      - name: lccenc3
        inputs_to_wait_for: 4
        output_policy: BATCHED_CUSTOM_ORDER
        children:
          - score3a
          - score3b
          - score3c
        infile_prefix: storeclass3
        outfile_prefix: lccenc3
        dag_task: True
      - name: lccenc4
        inputs_to_wait_for: 4
        output_policy: BATCHED_CUSTOM_ORDER
        children:
          - score4a
          - score4b
          - score4c
        infile_prefix: storeclass4
        outfile_prefix: lccenc4
        dag_task: True
      - name: lccenc5
        inputs_to_wait_for: 4
        output_policy: BATCHED_CUSTOM_ORDER
        children:
          - score5a
          - score5b
          - score5c
        infile_prefix: storeclass5
        outfile_prefix: lccenc5
        dag_task: True
      - name: score1a
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg1
        infile_prefix: lccenc1
        outfile_prefix: score1a
        dag_task: True
      - name: score1b
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg1
        infile_prefix: lccenc1
        outfile_prefix: score1b
        dag_task: True
      - name: score1c
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg1
        infile_prefix: lccenc1
        outfile_prefix: score1c
        dag_task: True
      - name: score2a
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg2
        infile_prefix: lccenc2
        outfile_prefix: score2a
        dag_task: True
      - name: score2b
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg2
        infile_prefix: lccenc2
        outfile_prefix: score2b
        dag_task: True
      - name: score2c
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg2
        infile_prefix: lccenc2
        outfile_prefix: score2c
        dag_task: True
      - name: score3a
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg3
        infile_prefix: lccenc3
        outfile_prefix: score3a
        dag_task: True
      - name: score3b
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg3
        infile_prefix: lccenc3
        outfile_prefix: score3b
        dag_task: True
      - name: score3c
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg3
        infile_prefix: lccenc3
        outfile_prefix: score3c
        dag_task: True
      - name: score4a
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg4
        infile_prefix: lccenc4
        outfile_prefix: score4a
        dag_task: True
      - name: score4b
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg4
        infile_prefix: lccenc4
        outfile_prefix: score4b
        dag_task: True
      - name: score4c
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg4
        infile_prefix: lccenc4
        outfile_prefix: score4c
        dag_task: True
      - name: score5a
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg5
        infile_prefix: lccenc5
        outfile_prefix: score5a
        dag_task: True
      - name: score5b
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg5
        infile_prefix: lccenc5
        outfile_prefix: score5b
        dag_task: True
      - name: score5c
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg5
        infile_prefix: lccenc5
        outfile_prefix: score5c
        dag_task: True
      - name: preagg1
        inputs_to_wait_for: 3
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - lccdec1
        infile_prefix: score1
        outfile_prefix: preagg1
        dag_task: True
      - name: preagg2
        inputs_to_wait_for: 3
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - lccdec2
        infile_prefix: score2
        outfile_prefix: preagg2
        dag_task: True
      - name: preagg3
        inputs_to_wait_for: 3
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - lccdec3
        infile_prefix: score3
        outfile_prefix: preagg3
        dag_task: True
      - name: preagg4
        inputs_to_wait_for: 3
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - lccdec4
        infile_prefix: score4
        outfile_prefix: preagg4
        dag_task: True
      - name: preagg5
        inputs_to_wait_for: 3
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - lccdec5
        infile_prefix: score5
        outfile_prefix: preagg5
        dag_task: True
      - name: lccdec1
        inputs_to_wait_for: 2
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - home
        infile_prefix: preagg1
        outfile_prefix: lccdec1
        dag_task: True
      - name: lccdec2
        inputs_to_wait_for: 2
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - home
        infile_prefix: preagg2
        outfile_prefix: lccdec2
        dag_task: True
      - name: lccdec3
        inputs_to_wait_for: 2
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - home
        infile_prefix: preagg3
        outfile_prefix: lccdec3
        dag_task: True
      - name: lccdec4
        inputs_to_wait_for: 2
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - home
        infile_prefix: preagg4
        outfile_prefix: lccdec4
        dag_task: True
      - name: lccdec5
        inputs_to_wait_for: 2
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - home
        infile_prefix: preagg5
        outfile_prefix: lccdec5
        dag_task: True
     